<?php

class AdressTableSeeder extends Seeder
{

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		// DB::table('courses')->truncate();

		$adress = array(
			['id'   	      => 1,
			'department_id'   => 1,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 2,
			'department_id'   => 2,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 3,
			'department_id'   => 3,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 4,
			'department_id'   => 4,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 5,
			'department_id'   => 5,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 6,
			'department_id'   => 6,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 7,
			'department_id'   => 7,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 8,
			'department_id'   => 8,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 9,
			'department_id'   => 9,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 10,
			'department_id'   => 10,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 11,
			'department_id'   => 11,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 12,
			'department_id'   => 12,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 13,
			'department_id'   => 13,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 14,
			'department_id'   => 14,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 15,
			'department_id'   => 15,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 16,
			'department_id'   => 16,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 17,
			'department_id'   => 17,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 18,
			'department_id'   => 18,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 19,
			'department_id'   => 19,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 20,
			'department_id'   => 20,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 21,
			'department_id'   => 21,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 22,
			'department_id'   => 22,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 23,
			'department_id'   => 23,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 24,
			'department_id'   => 24,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 25,
			'department_id'   => 25,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 26,
			'department_id'   => 26,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 27,
			'department_id'   => 27,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 28,
			'department_id'   => 28,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 29,
			'department_id'   => 29,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 30,
			'department_id'   => 30,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 31,
			'department_id'   => 31,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 32,
			'department_id'   => 32,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 33,
			'department_id'   => 33,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 34,
			'department_id'   => 34,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 35,
			'department_id'   => 35,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 36,
			'department_id'   => 36,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 37,
			'department_id'   => 37,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 38,
			'department_id'   => 38,
			'en'        	  => 'Chyngyz Aytmatov Campus, Djal,<br/> Bishkek, Kyrgyzstan 
Phone +996(312) 49 2761, Fax +996(312) 49 2761, e-mail: @manas.edu.kg',
			'tr'        	  => 'Cengiz Aytmatov Cal Kampüsü, Bişkek, Kırgızistan, Telefon +996(312) 49 2761, e-posta: @manas.edu.kg',
			'kg'        	  => 'Чынгыз Айтматов атындагы кампус, Джал, Бишкек, Кыргыз Республикасы, тел. +996(312)49 2761',
			'ru'        	  => 'Кампус им. Чынгыза Айтматова, Джал, Бишкек, Кыргызская Республика, тел. +996(312)49 2761',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
		);

		// Uncomment the below to run the seeder
		DB::table('adress')->insert($adress);
	}

}