 <?php 

class  InfoTableSeeder extends Seeder
 {  

 	public function  run()  
	 {
		// Uncomment the below to wipe the table clean before populating
 		// DB::table('Infoes')->truncate();   

		$Info = array (
		 	
			['id'          => 1,
			'type'		   => 1,
			'department_id'=> 24,
			'title' 	   => 'Info 1',
			'en'		   => 'Info 1',
			'kg'		   => 'Маалымат 1',
			'tr'		   => 'Bilgi 1',
			'ru'		   => 'Информация 1',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 2,
			'type'		   => 2,
			'department_id'=> 24,
			'title' 	   => 'For Prospective Students 1',
			'en'		   => 'For Prospective Students 1',
			'kg'		   => 'Абитуриенттер үчүн маалымат 1',
			'tr'		   => 'Aday Öğrenciler için 1',
			'ru'		   => 'Информация для абитуриентов 1',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 3,
			'type'		   => 1,
			'department_id'=> 24,
			'title' 	   => 'Info 2',
			'en'		   => 'Info 1',
			'kg'		   => 'Маалымат 1',
			'tr'		   => 'Bilgi 1',
			'ru'		   => 'Информация 1',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 4,
			'type'		   => 3,
			'department_id'=> 24,
			'title' 	   => 'History 1',
			'en'		   => 'Info 1',
			'kg'		   => 'Маалымат 1',
			'tr'		   => 'Bilgi 1',
			'ru'		   => 'Информация 1',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 5,
			'type'		   => 1,
			'department_id'=> 24,
			'title' 	   => 'Info 3',
			'en'		   => 'Info 1',
			'kg'		   => 'Маалымат 1',
			'tr'		   => 'Bilgi 1',
			'ru'		   => 'Информация 1',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 6,
			'type'		   => 2,
			'department_id'=> 24,
			'title' 	   => 'For Prospective Students 2',
			'en'		   => 'For Prospective Students 2',
			'kg'		   => 'Абитуриенттер үчүн маалымат 2',
			'tr'		   => 'Aday Öğrenciler için 2',
			'ru'		   => 'Информация для абитуриентов 2',
			'description_en' => 'Here goes some info in English.',
			'description_kg' => 'Here goes some info in Kyrgyz.',
			'description_tr' => 'Here goes some info in Turkish.',
			'description_ru' => 'Here goes some info in Russian.'],
			['id'          => 11,
			'type'		   => 11,
			'department_id'=> 24,
			'title' 	   => 'Vision ans Mission',
			'en'		   => 'Vision ans Mission',
			'kg'		   => 'Маалымат 1 Vision ans Mission',
			'tr'		   => 'Bilgi 1 Vision ans Mission',
			'ru'		   => 'Информация 1 Vision ans Mission',
			'description_en' => 'Our Vision ans Mission in English.',
			'description_kg' => 'Our Vision ans Mission in Kyrgyz.',
			'description_tr' => 'Our Vision ans Mission in Turkish.',
			'description_ru' => 'Our Vision ans Mission in Russian.'],			
			['id'          => 12,
			'type'		   => 12,
			'department_id'=> 24,
			'title' 	   => 'Administration',
			'en'		   => 'Administration',
			'kg'		   => 'Маалымат 1 Administration',
			'tr'		   => 'Bilgi 1 Administration',
			'ru'		   => 'Информация 1 Administration',
			'description_en' => 'Our Administration in English.',
			'description_kg' => 'Our Administration in Kyrgyz.',
			'description_tr' => 'Our Administration in Turkish.',
			'description_ru' => 'Our Administration in Russian.'],	
			['id'          => 13,
			'type'		   => 13,
			'department_id'=> 24,
			'title' 	   => 'Committees',
			'en'		   => 'Committees',
			'kg'		   => 'Маалымат 1 Committees',
			'tr'		   => 'Bilgi 1 Committees',
			'ru'		   => 'Информация 1 Committees',
			'description_en' => 'Our Committees in English.',
			'description_kg' => 'Our Committees in Kyrgyz.',
			'description_tr' => 'Our Committees in Turkish.',
			'description_ru' => 'Our Committees in Russian.'],	
			['id'          => 14,
			'type'		   => 14,
			'department_id'=> 24,
			'title' 	   => 'Department by Numbers',
			'en'		   => 'Department by Numbers',
			'kg'		   => 'Маалымат 1 Department by Numbers',
			'tr'		   => 'Bilgi 1 Department by Numbers',
			'ru'		   => 'Информация 1 Department by Numbers',
			'description_en' => 'Our Department by Numbers in English.',
			'description_kg' => 'Our Department by Numbers in Kyrgyz.',
			'description_tr' => 'Our Department by Numbers in Turkish.',
			'description_ru' => 'Our Department by Numbers in Russian.'],
			['id'          => 15,
			'type'		   => 15,
			'department_id'=> 24,
			'title' 	   => 'Accreditation',
			'en'		   => 'Accreditation',
			'kg'		   => 'Маалымат 1 Accreditation',
			'tr'		   => 'Bilgi 1 Accreditation',
			'ru'		   => 'Информация 1 Accreditation',
			'description_en' => 'Our Accreditation in English.',
			'description_kg' => 'Our Accreditation in Kyrgyz.',
			'description_tr' => 'Our Accreditation in Turkish.',
			'description_ru' => 'Our Accreditation in Russian.'],
		);    

		// Un comment the below to run the seeder
		DB::table('Info')->insert($Info);
	}
}