<?php

class MenuTableSeeder extends Seeder
{

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		// DB::table('menu')->truncate();

		$menu = array(
			['id'       => 1,
			'parent_id' => 0,
			'kg'		=> 'Маалымат',
			'ru'		=> 'Информация',
			'en'		=> 'Info',
			'tr'		=> 'Bilgi',
			'url'		=> '/infos/24'],
			['id'       => 2,
			'parent_id' => 0,
			'kg'		=> 'Кызматчылар',
			'ru'		=> 'Сотрудники',
			'en'		=> 'People',
			'tr'		=> 'Kişiler',
			'url'		=> '/teachers/24'],
			['id'       => 3,
			'parent_id' => 0,
			'kg'		=> 'Сабактар',
			'ru'		=> 'Курсы',
			'en'		=> 'Courses',
			'tr'		=> 'Dersler',
			'url'		=> '/courses/24'],
			['id'       => 4,
			'parent_id' => 0,
			'kg'		=> 'Изилдөө', 
			'ru'		=> 'Исследования',
			'en'		=> 'Researches',
			'tr'		=> 'Araştırma',
			'url'		=> '/researches/24'],
			['id'       => 5,
			'parent_id' => 0,
			'kg'		=> 'Абитуриенттер',
			'ru'		=> 'Абитуриенты',
			'en'		=> 'Prospectıve Students',
			'tr'		=> 'Aday Öğrenciler',
			'url'		=> '/prosp_students/24/2'],
			['id'       => 6,
			'parent_id' => 0,
			'kg'		=> 'Байланыш',
			'ru'		=> 'Контакты',
			'en'		=> 'Contact Us',
			'tr'		=> 'İletişim',
			'url'		=> '/contacts/24'],

			['id'       => 10,
			'parent_id' => 1,
			'kg'		=> 'Актуалдуу',
			'ru'		=> 'Актуальная',
			'en'		=> 'Current',
			'tr'		=> 'Güncel',
			'url'		=> '/infos/24'],
			['id'       => 11,
			'parent_id' => 1,
			'kg'		=> 'Тарых',
			'ru'		=> 'История',
			'en'		=> 'History',
			'tr'		=> 'Tarih',
			'url'		=> '/infos/24'],
			['id'       => 101,
			'parent_id' => 10,
			'kg'		=> 'Миссия жана Стратегия',
			'ru'		=> 'Миссия и Стратегия',
			'en'		=> 'Vision and Mission',
			'tr'		=> 'Uzgörü ve Özgörev',
			'url'		=> '/infos/24'],
			['id'       => 102,
			'parent_id' => 10,
			'kg'		=> 'Башкаруу',
			'ru'		=> 'Управление',
			'en'		=> 'Administration',
			'tr'		=> 'Yönetim',
			'url'		=> '/infos/24'],
			['id'       => 103,
			'parent_id' => 10,
			'kg'		=> 'Комитеттер',
			'ru'		=> 'Комитеты',
			'en'		=> 'Committees',
			'tr'		=> 'Komiteler',
			'url'		=> '/infos/24'],
			['id'       => 104,
			'parent_id' => 10,
			'kg'		=> 'Сан менен Бөлүм',
			'ru'		=> 'Отделение в Числаж',
			'en'		=> 'Department By Numbers',
			'tr'		=> 'Sayılarla Bölüm',
			'url'		=> '/infos/24'],
			['id'       => 105,
			'parent_id' => 10,
			'kg'		=> 'Аккредитация',
			'ru'		=> 'Аккредитация',
			'en'		=> 'Accreditation',
			'tr'		=> 'Akreditasyon',
			'url'		=> '/infos/24'],
			['id'       => 110,
			'parent_id' => 11,
			'kg'		=> 'Тарых',
			'ru'		=> 'История',
			'en'		=> 'History',
			'tr'		=> 'Tarihçe',
			'url'		=> '/infos/24'],
			['id'       => 111,
			'parent_id' => 11,
			'kg'		=> 'Мурдакы Бөлүм Башчылары',
			'ru'		=> 'Предыдущие Заведующие',
			'en'		=> 'Past Chairpersons',
			'tr'		=> 'Önceki Bölüm Başkanları',
			'url'		=> '/infos/24'],
			['id'       => 20,
			'parent_id' => 2,
			'kg'		=> 'Мугалимдер',
			'ru'		=> 'Преподаватели',
			'en'		=> 'Faculty',
			'tr'		=> 'Öğretim Elemanları',
			'url'		=> '/teachers/24'],
			['id'       => 21,
			'parent_id' => 2,
			'kg'		=> 'Кенже Илимий Кызматкердер',
			'ru'		=> 'Младшие Научные Сотрудники',
			'en'		=> 'Assistants',
			'tr'		=> 'Asistanlar',
			'url'		=> '/teachers/24'],

			
			
		);

		// Uncomment the below to run the seeder
		DB::table('menu')->insert($menu);
	}

}
